import { Platform, StyleSheet } from "react-native";
import { Color, Font } from "../../../utils/theme";

const styles = StyleSheet.create({
  contentMain: {
    flex: 1,
    backgroundColor: Color.GREY_100,
  },
  addressView: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: Color.WHITE,
  },
  locationText: {
    fontFamily: Font.SFPROTEXTSEMIBOLD,
    fontSize: Font.SIZE_22,
    color: Color.GREY_900,
  },
  timeAddress: {
    fontFamily: Font.SFPROTEXTREGULAR,
    fontSize: Font.SIZE_12,
    color: Color.GREY_600,
    marginTop: 8,
  },
  sendIcon: {
    marginTop: 8,
    fontSize: Font.SIZE_22,
    color: Color.BLUE_500,
  },
  detailsPart: {
    flexWrap: "wrap",
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: Color.WHITE,
  },
  detailConten: {
    marginTop: 16,
    width: "32%",
    borderLeftWidth: 1,
    borderLeftColor: Color.GREY_200,
    paddingHorizontal: 8,
  },
  textAlign: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "flex-start",
  },
  numberText: {
    fontFamily: Font.SFPROTEXTBOLD,
    fontSize: Font.SIZE_16,
    color: Color.GREY_900,
  },
  healthText: {
    fontFamily: Font.SFPROTEXTSEMIBOLD,
    fontSize: Font.SIZE_18,
    color: Color.GREY_900,
  },
  healthSubText: {
    fontFamily: Font.SFPROTEXTREGULAR,
    fontSize: Font.SIZE_18,
    color: Color.GREY_500,
    marginLeft: 5,
  },
  map: {
    height: 375,
  },
  healthPart: {
    paddingHorizontal: 16,
    paddingTop: 16,
    backgroundColor: Color.WHITE,
    marginTop: 8,
    marginBottom: 8,
  },
  healthPartList: {
    marginVertical: 16,
    flexWrap: "wrap",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  liveViewBack: {
    backgroundColor: Color.WHITE,
    paddingHorizontal: 16,
  },
  liveViewBorder: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: Color.GREY_200,
    paddingVertical: 14,
  },
  liveViewNoBorder: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
  },
  iconTextStyle: {
    fontFamily: Font.SFPROTEXTMEDIUM,
    fontSize: Font.SIZE_14,
    color: Color.GREY_700,
  },
  texWithIcon: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  liveView: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  modalView: {
    marginTop: "auto",
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    backgroundColor: Color.WHITE,
    ...Platform.select({
      ios: {
        shadowColor: "#003362",
        shadowOffset: {
          width: 0,
          height: 6,
        },
        shadowOpacity: 0.08,
        shadowRadius: 24,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  line: {
    marginVertical: 8,
    width: 92,
    height: 4,
    borderRadius: 2,
    backgroundColor: Color.GREY_300,
    alignSelf: "center",
  },
  delayStartText: {
    marginTop: 4,
    paddingHorizontal: 16,
    marginBottom: 20,
    fontFamily: Font.SFPROTEXTSEMIBOLD,
    fontSize: Font.SIZE_18,
    color: Color.GREY_700,
  },
  listText: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 13,
    borderBottomWidth: 1,
    borderBottomColor: Color.GREY_200,
  },
  itemText: {
    fontFamily: Font.SFPROTEXTMEDIUM,
    fontSize: Font.SIZE_14,
    lineHeight: 20,
  },
  checkIconStyle: {
    fontSize: Font.SIZE_18,
    color: Color.BLUE_500,
  },
  rightTextStyle: {
    fontFamily: Font.SFPROTEXTMEDIUM,
    fontSize: Font.SIZE_14,
    color: Color.GREY_600,
  },
  rightIconStyle: {
    color: Color.BLUE_500,
    fontSize: Font.SIZE_18,
    marginLeft: 8,
  },
  speedSplit: {
    backgroundColor: Color.WHITE,
    padding: 16,
    marginBottom: 8,
    marginTop: 8,
  },
  titleWithTab: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  speedWithkm: {
    flexDirection: "row",
    justifyContent: "flex-start",
  },
  segmentedControlTabStyleBack: {
    width: 166,
    paddingVertical: 2,
    paddingHorizontal: 2,
    backgroundColor: Color.GREY_200,
    borderRadius: 18,
  },
  tabsContainerStyle: {
    height: 32,
  },
  firstTabStyle: {
    borderRightWidth: 0,
  },
  tabStyle: {
    borderRadius: 16,
    borderWidth: 0,
    backgroundColor: Color.TRANSPARENT,
  },
  tabTextStyle: {
    fontFamily: Font.SFPROTEXTREGULAR,
    fontSize: Font.SIZE_12,
    color: Color.GREY_700,
    borderWidth: 0,
  },
  activeTabStyle: {
    borderWidth: 0,
    backgroundColor: Color.WHITE,
    ...Platform.select({
      ios: {
        shadowColor: "#003362",
        shadowOffset: {
          width: 0,
          height: 3,
        },
        shadowOpacity: 0.06,
        shadowRadius: 6,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  activeTabTextStyle: {
    fontFamily: Font.SFPROTEXTSEMIBOLD,
    fontSize: Font.SIZE_12,
    color: Color.BLUE_500,
  },
  tableHeaderMain: {
    marginTop: 16,
    borderBottomWidth: 1,
    borderBottomColor: Color.GREY_200,
    paddingVertical: 10,
  },
  tableBodyMain: {
    borderBottomWidth: 1,
    borderBottomColor: Color.GREY_200,
    paddingVertical: 10,
  },
  tableHeaderPart: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerTitle: {
    fontFamily: Font.SFPROTEXTREGULAR,
    fontSize: Font.SIZE_12,
    color: Color.GREY_700,
    width: "65%",
  },
  headerTitleTwo: {
    fontFamily: Font.SFPROTEXTREGULAR,
    fontSize: Font.SIZE_12,
    color: Color.GREY_700,
    width: "20%",
  },
  headerTitleThree: {
    fontFamily: Font.SFPROTEXTREGULAR,
    fontSize: Font.SIZE_12,
    color: Color.GREY_700,
    width: "15%",
    textAlign: "center",
  },
  splitsPart: {
    paddingTop: 16,
    backgroundColor: Color.WHITE,
    marginTop: 16,
    paddingHorizontal: 16,
  },
  tagsPart: {
    flexDirection: "column",
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: Color.WHITE,
    marginBottom: 8,
  },
  editIconStyle: {
    fontSize: Font.SIZE_18,
    color: Color.BLUE_500,
  },
  inputContainerMainStyle: {
    marginBottom: 0,
  },
  inputContainerStyle: {
    marginTop: 6,
    height: "auto",
    borderBottomWidth: 0,
  },
  inputStyle: {
    fontFamily: Font.SFPROTEXTREGULAR,
    color: Color.GREY_700,
    marginBottom: 0,
  },
  saveBtnText: {
    fontFamily: Font.SFPROTEXTREGULAR,
    fontSize: Font.SIZE_14,
    color: Color.BLUE_500,
  },
  chart: {
    height: 130,
    width: "100%",
    marginBottom: 16,
    marginTop: 16,
  },
  circleMarker: {
    backgroundColor: Color.BLUE,
    alignItems: "center",
    justifyContent: "center",
    height: 24,
    width: 24,
    borderRadius: 12,
    borderColor: Color.WHITE,
    borderWidth: 3,
  },
  sourceCircleMarker: {
    backgroundColor: Color.RED_100,
    alignItems: "center",
    justifyContent: "center",
    height: 24,
    width: 24,
    borderRadius: 12,
    borderColor: Color.WHITE,
    borderWidth: 3,
  },
  destinatonCircleMarker: {
    backgroundColor: Color.GREEN_100,
    alignItems: "center",
    justifyContent: "center",
    height: 24,
    width: 24,
    borderRadius: 12,
    borderColor: Color.WHITE,
    borderWidth: 3,
  },
  tagListContainer: {
    flexDirection: "row",
    width: "100%",
    justifyContent: "flex-start",
    flexWrap: "wrap",
  },
  tagContainer: {
    position: "relative",
    top: -5,
    width: "auto",
    borderRadius: 12,
    backgroundColor: Color.GREY_200,
    paddingHorizontal: 8,
    paddingVertical: 5,
    marginRight: 8,
    marginBottom: 4,
  },
  tagText: {
    fontFamily: Font.SFPROTEXTMEDIUM,
    fontSize: Font.SIZE_12,
    color: Color.GREY_900,
    position: "relative",
    top: -1,
  },
  textInput: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: Color.WHITE,
    fontSize: Font.SIZE_14,
    borderRadius: 5,
    borderWidth: 0.5,
    borderColor: "#3c3c434d",
    marginBottom: 20,
    marginTop: 16,
  },
  buttonContainer: {
    alignItems: "flex-end",
  },
  buttonStyle: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    height: "auto",
  },
  buttonTitleStyle: {
    fontSize: Font.SIZE_12,
  },
  editTagContainer: {
    width: "auto",
    borderRadius: 12,
    backgroundColor: Color.GREY_200,
    paddingHorizontal: 8,
    paddingVertical: 5,
    marginRight: 8,
    marginBottom: 4,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  crossIcon: {
    marginLeft: 2,
    fontSize: Font.SIZE_12,
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
  MarkerText: {
    position: "relative",
    fontFamily: Font.SFPROTEXTMEDIUM,
    fontSize: Font.SIZE_10,
    color: Color.WHITE,
  },
  modalTitleStyle: {
    alignSelf: "center",
  },
  modalTxtStyle: {
    alignSelf: "center",
    textAlign: "center",
  }
});

export default styles;
