export const ADD_SESSION_TYPE = 'ADD_SESSION_TYPE';
export const GET_SESSION_TYPE = 'GET_SESSION_TYPE';
export const SET_SESSION_TYPE = 'SET_SESSION_TYPE';
export const EDIT_SESSION_TYPE = 'EDIT_SESSION_TYPE';
export const DELETE_SESSION_TYPE = 'DELETE_SESSION_TYPE';