export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const SHOW_TOAST = 'SHOW_TOAST';
export const HIDE_TOAST = 'HIDE_TOAST';

export const SWITCH_PROFILE = 'SWITCH_PROFILE';
export const IS_BACK_BUTTON_CLICK = 'IS_BACK_BUTTON_CLICK';

export const IS_FROM_SIGNOUT = 'IS_FROM_SIGNOUT'
export const SHOW_LOGIN_MESSAGE = 'SHOW_LOGIN_MESSAGE'
